In [8]:
from sklearn.preprocessing import MinMaxScaler
import h5py
import numpy

def get_dataset_name(file_name_with_dir):
    file_name_without_dir = file_name_with_dir.split('/')[-1]
    temp = file_name_without_dir.split('_')[:-1]
    dataset_name = "_".join(temp)
    return dataset_name

#replace with local path
filename_path = "data/pdata/Intra/train/rest_105923_1.h5"
with h5py.File(filename_path, 'r') as f:
    dataset_name = get_dataset_name(filename_path)
    matrix = f.get(dataset_name)[()]
    print(type(matrix))
    print(matrix.shape) 

scaler = MinMaxScaler(feature_range=(0, 1))
scaler.fit(matrix)
scaled_data = scaler.transform(matrix)
print(scaled_data)



<class 'numpy.ndarray'>
(248, 35624)
[[0.75709679 0.75655099 0.75461831 ... 0.75787271 0.75722762 0.76213064]
 [0.57519353 0.56595376 0.55152292 ... 0.48226206 0.48329766 0.48382933]
 [0.76639813 0.76220723 0.75976352 ... 0.73835103 0.73913462 0.74171893]
 ...
 [0.78054736 0.78005406 0.77447601 ... 0.78332417 0.77990748 0.78139679]
 [0.5291242  0.52498386 0.51793955 ... 0.47161298 0.46912766 0.47366007]
 [0.49634087 0.48903129 0.47857    ... 0.5523971  0.55285888 0.55528368]]
